import 'package:flutter/material.dart';
final Color colorprimary = Colors.blue.shade600;
final Color colorprimarymid = Colors.blue.shade300;
final Color colorprimarylight = Colors.blue.shade100;
final Color colorsec = Colors.green.shade600;
final Color colorsecmid = Colors.green.shade300;
final Color colorwhite = Colors.white;
final Color colorblack = Colors.black;
final Color colorgreydark = Colors.black54;
final Color colorgreylight = Colors.grey.shade200;
final Color colorhover = Colors.pink.shade100;